sudo: required
language: minimal

services:
  - docker

script: make docker-build

deploy:
  - provider: script
    script: docker login -u=slamdev -p="$DOCKER_PASSWORD" && make docker-release
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
